// Computed metrics from the personal loan dataset (500 customers).
// These values are generated by the Python EDA and embedded here
// so the dashboard can display the analysis results without a backend.

export const metrics = {
  total: 500,
  avgAge: 45.0,
  avgIncome: 81.1,
  avgCCAvg: 3.22,
  avgMortgage: 31.2,
  loanRate: 19.4,
};

export const byEducation = [
  { label: "Undergraduate", rate: 13.4, count: 216 },
  { label: "Graduate", rate: 22.7, count: 150 },
  { label: "Advanced / Professional", rate: 25.4, count: 134 },
];

export const byIncome = [
  { label: "Low income", rate: 7.7, count: 168 },
  { label: "Medium income", rate: 13.3, count: 165 },
  { label: "High income", rate: 37.1, count: 167 },
];

export const byAge = [
  { label: "Under 30", rate: 22.7, count: 44 },
  { label: "30-40", rate: 22.7, count: 132 },
  { label: "40-50", rate: 17.4, count: 172 },
  { label: "50-60", rate: 19.3, count: 109 },
  { label: "Over 60", rate: 14.0, count: 43 },
];

export const byFamily = [
  { label: "Single (1)", rate: 15.7, count: 115 },
  { label: "Small (2)", rate: 20.9, count: 158 },
  { label: "Medium (3)", rate: 16.4, count: 140 },
  { label: "Large (4)", rate: 26.4, count: 87 },
];

export const byProduct = [
  { label: "CD Account", yesRate: 37.1, noRate: 18.1, yesCount: 35, noCount: 465 },
  { label: "Securities Account", yesRate: 25.0, noRate: 18.7, yesCount: 56, noCount: 444 },
  { label: "Online Banking", yesRate: 20.4, noRate: 17.9, yesCount: 299, noCount: 201 },
  { label: "Credit Card", yesRate: 19.2, noRate: 19.5, yesCount: 156, noCount: 344 },
];

export const correlations = [
  { feature: "Income", value: 0.395 },
  { feature: "CCAvg", value: 0.378 },
  { feature: "Education", value: 0.129 },
  { feature: "CD Account", value: 0.123 },
  { feature: "Family", value: 0.061 },
  { feature: "Securities Account", value: 0.05 },
  { feature: "Online", value: 0.031 },
  { feature: "CreditCard", value: -0.003 },
  { feature: "Mortgage", value: -0.048 },
  { feature: "Experience", value: -0.05 },
  { feature: "Age", value: -0.053 },
];

export const insights = [
  {
    title: "Income is the strongest driver",
    text: "High-income customers accepted personal loans at 37.1% vs only 7.7% for low-income — a 29.4 percentage-point gap.",
    icon: "DollarSign",
  },
  {
    title: "Education raises acceptance",
    text: "Advanced/Professional customers accepted at 25.4% compared to 13.4% for undergraduates.",
    icon: "GraduationCap",
  },
  {
    title: "CD account holders are prime targets",
    text: "Customers with a CD account accepted at 37.1% vs 18.1% for non-holders — existing deposit customers trust the bank.",
    icon: "PiggyBank",
  },
  {
    title: "Credit card spending correlates",
    text: "CCAvg has the second-highest correlation with loan acceptance (0.378), after income (0.395).",
    icon: "CreditCard",
  },
  {
    title: "Large families accept more",
    text: "Family size 4 shows the highest acceptance at 26.4%, likely due to greater financial needs.",
    icon: "Users",
  },
  {
    title: "Online banking is a good channel",
    text: "Online banking users accept at 20.4% vs 17.9% for non-users — digital channels are effective for loan campaigns.",
    icon: "Wifi",
  },
  {
    title: "Securities account holders are receptive",
    text: "Securities account holders accepted at 25.0% vs 18.7% — investment-savvy customers are more open to credit.",
    icon: "TrendingUp",
  },
  {
    title: "Age has a weak effect",
    text: "The 30-40 and under-30 groups show the highest acceptance (22.7%), but age alone is not a strong predictor.",
    icon: "Calendar",
  },
];

export const executiveSummary = {
  findings: [
    "500 customers analyzed with 14 attributes covering demographics, financial behavior, and product holdings.",
    "19.4% of customers accepted a personal loan during the campaign.",
    "Income is the strongest driver: high-income customers accepted at 37.1% vs 7.7% for low-income.",
    "Education matters: acceptance rises from 13.4% (undergraduate) to 25.4% (advanced/professional).",
    "CD account holders accept at 37.1% vs 18.1% for non-holders.",
  ],
  segments: [
    { name: "High income + higher education", reason: "Highest acceptance rate — prime target" },
    { name: "CD account holders", reason: "Already trust the bank with deposits" },
    { name: "Securities account holders", reason: "Investment-savvy, receptive to credit" },
    { name: "Age 30-40", reason: "Peak acceptance among age groups" },
  ],
  recommendations: [
    "Target the high-value segment (high income + graduate/advanced education) first.",
    "Cross-sell to existing deposit customers (CD account holders).",
    "Use online banking channels to deliver loan offers efficiently.",
    "Design income-tiered offers instead of one-size-fits-all loans.",
    "Future improvement: build a simple ML model to predict loan acceptance (optional, beyond this EDA).",
  ],
};
